package com.astralplayer.nextplayer.data.entities

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "subtitles")
data class SubtitleEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val videoPath: String,
    val language: String,
    val subtitlePath: String?,
    val isAutoGenerated: Boolean = false
)