package com.astralplayer.nextplayer.bookmark

import androidx.room.Entity
import androidx.room.PrimaryKey
import kotlinx.serialization.Serializable

/**
 * Bookmark entity for storing video bookmarks
 */
@Entity(tableName = "bookmarks")
@Serializable
data class VideoBookmark(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val videoUri: String,
    val videoTitle: String,
    val position: Long, // Position in milliseconds
    val duration: Long, // Total duration in milliseconds
    val title: String,
    val note: String? = null,
    val thumbnailPath: String? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val color: Int = 0xFF2196F3.toInt(), // Default blue color
    val isChapter: Boolean = false // Chapters are special bookmarks
)

/**
 * Chapter entity - chapters are bookmarks with additional metadata
 */
@Serializable
data class VideoChapter(
    val bookmark: VideoBookmark,
    val chapterIndex: Int,
    val endPosition: Long? = null // End position for the chapter
) {
    init {
        require(bookmark.isChapter) { "Chapter must be created from a bookmark with isChapter=true" }
    }
}

/**
 * Video chapters collection
 */
@Serializable
data class VideoChapters(
    val videoUri: String,
    val videoTitle: String,
    val chapters: List<VideoChapter>,
    val autoGenerated: Boolean = false
)