package com.astralplayer.nextplayer.models

data class VideoInfo(
    val path: String,
    val title: String,
    val duration: Long,
    val size: Long,
    val resolution: String,
    val format: String,
    val codec: String,
    val bitrate: Long,
    val frameRate: Float
)

data class SubtitleInfo(
    val language: SubtitleLanguage,
    val path: String? = null,
    val isEmbedded: Boolean = false,
    val isAutoGenerated: Boolean = false
)

data class StreamingConfig(
    val url: String,
    val headers: Map<String, String> = emptyMap(),
    val userAgent: String? = null,
    val referer: String? = null,
    val isLiveStream: Boolean = false
)

data class PlayerSettings(
    val defaultQuality: VideoQuality = VideoQuality.AUTO,
    val defaultSpeed: PlaybackSpeed = PlaybackSpeed.SPEED_1X,
    val defaultAspectRatio: AspectRatio = AspectRatio.ASPECT_RATIO_DEFAULT,
    val decoderType: DecoderType = DecoderType.AUTO,
    val autoPlay: Boolean = true,
    val rememberPosition: Boolean = true,
    val showSubtitles: Boolean = true,
    val subtitleLanguage: SubtitleLanguage = SubtitleLanguage.ENGLISH,
    val subtitleStyle: SubtitleStyle = SubtitleStyle.DEFAULT,
    val gesturesEnabled: Boolean = true,
    val brightnessGesture: Boolean = true,
    val volumeGesture: Boolean = true,
    val seekGesture: Boolean = true,
    val doubleTapSeek: Boolean = true,
    val doubleTapSeekDuration: Int = 10
)